export const ROUTES = {
  LOGIN:            "/login",
  REGISTER:         "/register",
  CHANGE_PASSWORD:  "/change-password",
  FORGOT_PASSWORD:  "/forgot-password",
  RESET_PASSWORD:   "/reset-password",
  DASHBOARD:        "/",
  EMPLOYEES:        "/employees",
  EMPLOYEE_DETAIL:  "/employees/:id",
  ATTENDANCE:       "/attendance",
  TIME_OFF:         "/time-off",
  PAYROLL:          "/payroll",
  REPORTS:          "/reports",
  SETTINGS:         "/settings",
};
